root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = "go build -o ./tmp/ cmd/ewallet/main.go"
  bin = "tmp/main"
  full_bin = "APP_ENV=dev APP_USER=air ./tmp/main start"
  poll = true
  # Watch these filename extensions.
  include_ext = ["go", "yaml", "env"]
  # Ignore these filename extensions or directories.
  exclude_dir = [".git", "tmp", "vendor", "test/node_modules"]
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000

  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false