services:
  postgres:
    image: postgres:alpine3.19
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ewallet
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
    command: [ "postgres", "-c", "log_statement=all" ]
volumes:
  data-volume:
    driver: local
